@baseUrl = http://localhost:5002/ 

get {{baseUrl}}products

###
post {{baseUrl}}products/create
Content-Type: application/json

{"name":"Kawasaki Vulcan S", "price": 47.000, "category":"654c3c33556effbd7c137ee3"}

###
post {{baseUrl}}categories/create
Content-Type: application/json

{
    "name":"Moveis", 
    "interestRate": 1
}
###
get {{baseUrl}}categories
###
DELETE {{baseUrl}}categories/

###
POST {{baseUrl}}products/plots/654c3cb1556effbd7c137eea
Content-Type: application/json

{
    "numberOfInstallments":12
}

###
curl -X GET -H "Content-Type: application/json" -d '{"price":100, "interestRate":10, "numberOfInstallments":12}' http://localhost:3000/products/:id/calculate

###
curl -X GET -H "Content-Type: application/json" -d '{"price":100, "interestRate":10, "numberOfInstallm"

curl -X POST -H "Content-Type: application/json" -d '{"name":"Produto1", "price": 50, "category":"categoria_id"}' http://localhost:3000/products'{"name":"Produto1", "price": 50, "category":"categoria_id"}'

